// <auto-generated />
using OpenPWCL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace OpenPWCL.Migrations
{
    [DbContext(typeof(TasksContext))]
    partial class TasksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OpenPWCL.Data.TaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Finished");

                    b.Property<string>("InputParams");

                    b.Property<string>("Resoult");

                    b.Property<Guid>("TaskId");

                    b.Property<Guid?>("TasksId");

                    b.HasKey("Id");

                    b.HasIndex("TasksId");

                    b.ToTable("TaskInstances");
                });

            modelBuilder.Entity("OpenPWCL.Data.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("JavascriptCode");

                    b.Property<string>("Name");

                    b.Property<string>("Priority");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("OpenPWCL.Data.TaskInstance", b =>
                {
                    b.HasOne("OpenPWCL.Data.Tasks")
                        .WithMany("TaskInstances")
                        .HasForeignKey("TasksId");
                });
#pragma warning restore 612, 618
        }
    }
}
